# This workflow performs linting, builds Docker container, and runs test suite for all branches
# And bandit security checks for master branch

name: Build and test

on:
  push:


env:
  PORT: ${{ secrets.PORT }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-lint.txt     
    - name: Run ruff check
      run: ruff check .
    - name: Run black check
      run: black --check .
    - name: Run isort check
      run: isort --check .

  test:
    runs-on: ubuntu-latest
    needs: lint

    env:
      DYNAMODB_HOST: http://dynamodb:8000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: fakeKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
      PORT: 5000

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker compose build
    - name: Run tests inside the container
      run: docker compose run --rm app pytest --cov=api tests/

  bandit-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    # Runs a pre configured Bandit scan 
    - name: Run bandit
      uses: jpetrucciani/bandit-check@master
      with:
        # only scans under this path
        path: './api'
